skinparam linetype ortho
left to right direction
skinparam classAttributeIconSize 0
abstract class Reception {}

class ReceptionController {
    ​CreateInvoice(roomId,date_in,date_out)
    PrintInvoice(roomId,date_out,Toal_fee)
}

class ServerController {
    ​CreateInvoice(roomId,date_in,date_out)​
    PrintInvoice(roomId,date_out,Toal_fee)
}
class Invoice {
    infolist
    create()
}


class ListManager {
    ​​CreateInvoice(roomId,date_in,date_out)
    PrintInvoice(roomId,date_out,Toal_fee)
}

Reception -- ReceptionController
ReceptionController -- ServerController
ServerController -- ListManager
ListManager o-- Invoice