skinparam linetype ortho
left to right direction
skinparam classAttributeIconSize 0
abstract class Reception {
    
}

class ReceptionController {
    CreateRDR(roomId,date_in,date_out)
    ​PrintRDR(roomId, list_RDR)
}

class ServerController {
    CreateRDR(roomId,date_in,date_out)
    ​PrintRDR(roomId, list_RDR)
}

class RDR {
    RDRinfolist
    create()
}

class ListManager {
    CreateRDR(roomId,date_in,date_out)
    ​PrintRDR(roomId, list_RDR)
}

Reception -- ReceptionController
ReceptionController -- ServerController
ServerController -- ListManager
ListManager o-- RDR