'空调 顾客 服务器 数据库 详单 管理员 前台 温度传感器 格式统计报表 优惠策略
skinparam linetype ortho
left to right direction
class 空调
class 顾客
class 服务器
class 数据库
class 详单
class 管理员
class 前台
class 温度传感器
class 工作人员
工作人员 <|-- 前台
工作人员 <|-- 管理员
服务器 "1"--"*" 工作人员
数据库 -- 服务器
空调 "*"--"1" 服务器
温度传感器 <--* 空调
顾客 "1"--"1" 空调
顾客 --> 前台
数据库 *--> 详单
数据库 *--> 统计报表
数据库 *--> 优惠策略