skinparam linetype ortho
left to right direction
skinparam classAttributeIconSize 0
class 客户端 {
    房号:string
    对应房间入住情况:string
    当前显示金额:string
    开启空调()
    关闭空调()
    控制空调状态()
    显示空调状态()
    显示金额()
}
class 顾客{
    手机号:string
    姓名:string
    身份证号:string
    房间号:string
    查看金额()
    索要详单账单()
    使用房间空调()
    入住客房()
    退房()
}
class 服务器{
    打印详单和账单()
    查看全部或指定房间内空调状态()
    修改全部或指定房间内空调状态()
    生成格式化报表()
    计算实时金额()
}
class 详单 {
    房间号:string
    运行时间:string
    对应金额:float
    运行信息:string
}
class 工作人员 {
    用户名:string
    密码:string
    操作服务器()
    登陆()
    注销()
}
class 管理员 {
    申请查看空调状态()
    申请修改空调状态()
    申请查看统计报表()
    申请查看详单()
}
class 前台 {
    申请办理入住()
    申请办理退房()
    申请查看空调状态()
    申请修改空调状态()
    申请查看统计报表()
    申请查看详单()
}
class 空调 {
    模式:string
    风速:int
    设定温度:int
    开机()
    关机()
    修改温度/模式/风速()
}
class 统计报表 {
    房间号:string
    运行时间:string
    对应金额:float
    运行信息:string
}
class 优惠策略 {
    房间号:string
    优惠幅度:float
}
工作人员 <|-- 前台
工作人员 <|-- 管理员
服务器 "1"--"*" 工作人员
客户端 "*"--"1" 服务器
空调 <--* 客户端
顾客 "1"--"1" 客户端
顾客 --> 前台
服务器 *--> 详单
服务器 *--> 统计报表
服务器 *--> 优惠策略