@startuml
'* 顾客打开空调
'* 空调向服务器发送开机命令
'* 服务器将空调设为开机状态，填充缺省状态
'* 后续客户可以自行调节空调的风速、温度，等待空调响应；
'* 服务器响应空调传来的调节信息，修改相关数据并反馈给空调
'* 空调响应
'* 空调周期性更新付费金额
|顾客|
start
fork
	:调整温度;
  fork again
	:调整风速;
  fork again
	:调整模式;
end fork
|客户端|
:等待响应;
|服务器|
:接收更改信号;
:进入响应等待队列;
:更新空调信息、金额计算并发送修改信号;
|客户端|
:接受响应更改信号;
|空调|
:状态修改;
stop

|服务器|
start 
while (每次心跳包)
  :发送更新金额信息;
  |客户端|
  :接收信息并更新金额显示;
end while
@enduml