@startuml
'* 顾客打开空调
'* 空调向服务器发送开机命令
'* 服务器将空调设为开机状态，填充缺省状态
'* 后续客户可以自行调节空调的风速、温度，等待空调响应；
'* 服务器响应空调传来的调节信息，修改相关数据并反馈给空调
'* 空调响应
'* 空调周期性更新付费金额
|顾客|
start
if (空调未开机) then (不使用空调)
 stop
else (使用空调)
  :开机;
  |空调|
  :接受开机指令;
  :传递消息到服务器;
  |服务器|
  :按缺省配置空调;
  |空调|
  :空调启动;
stop
@enduml