@startuml
'* 顾客提出退房请求
'* 前台查询空调状态，可强制关闭空调
'* 前台为客户打印详单并确定退房
'* 服务器修改相关数据
|顾客|
start
:提出退房住请求;
|前台|
if (查看空调状态) then (空调开机) 
  :关闭空调;
  |服务器|
  :接收空调关闭指令;
  |空调|
  :空调关闭;
  stop
endif
|前台|
:准备为客户打印详单;
|服务器|
:接收打印请求;
|前台|
:打印详单;
|顾客|
:确认详单信息;
:交付房卡;
:支付费用;
|前台|
:核对费用;
stop
@enduml