@startuml
'* 顾客提出入住请求
'* 前台查看剩余房间余量，若有空房则为顾客挑选房间
'* 顾客确认房间并提交个人信息入住，获得房卡
'* 前台确认顾客信息，确认入住，服务器修改相关信息
|顾客|
start
:提出入住请求;
|前台|
:查看剩余房间余量;
if (房间余量) then (无空房)
  :告知客户;
  |顾客|
  :离开;
  stop
else (有空房)
  :为客户挑选房间;
  |顾客|
  :确认房间;
  :提交个人信息;
  :获得房卡;
  |前台|
  :确认顾客信息;
  :确认顾客入住;
stop
@enduml