@startuml
'* 顾客提出入住请求
'* 前台查看剩余房间余量，若有空房则为顾客挑选房间
'* 顾客确认房间并提交个人信息入住，获得房卡
'* 前台确认顾客信息，确认入住，服务器修改相关信息
|顾客|
start
:提出入住请求;
:提交个人信息;
|前台|
:查看剩余房间余量;
:为客户挑选房间;
:确认顾客信息;
:将信息录入房卡;
|顾客|
:确认房间;
:获得房卡;
|前台|
:确认顾客入住;
stop
@enduml