@startuml

|业务|
start
fork
  |管理员|
  -[#blue]->
  :查看空调状态;
  |服务器|
  -[#blue]->
  :响应空调状态;
  -[#blue]->
  |管理员|
  :得到空调状态结果并查看;
fork again
  |前台|
  -[#green]->
  :生成详单账单;
  |服务器|
  -[#green]->
  :生成账单详单;
  |前台|
  -[#green]->
  :打印账单详单;
fork again
  |管理员|
  :格式统计报表;
  |服务器|
  :生成格式化统计报表;
  |管理员|
  :打印格式化统计报表;
end fork
stop
@enduml